### ISSUE TITLE
new role for WLS install

### ISSUE THREAD

**Issue by zeusbaba** [sysco-middleware/Dojo-Mini-Middleware#9]
new role for WLS install  `dojo-wls-install` 

plz use either `slim` or `lite`version of WLS `12.2.1.4`   
f.eks. here is how you can download slim  
```
# Download WebLogic Server Generic Installer 12.2.1.4
#
# - http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html
#
650109d90ab3da8f7a64b24a98e072b3 fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip

OR 
# Download WebLogic Server Slim Installer 12.2.1.4
#
# - http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html
#
df55639e00817308be249af5aa602bfb fmw_12.2.1.4.0_wls_quick_slim_Disk1_1of1.zip
```

**Comment by dhayanands** [comment]
@zeusbaba we already have a role to install - [dojo-fmw-installer](https://github.com/sysco-middleware/Dojo-Mini-Middleware/tree/develop/ansible-fmw/roles/dojo-fmw-installer). DO you want me to create a new one or modify the existing one?

**Comment by zeusbaba** [comment]
the existing role installs `fmw_infrastructure`,  but we need WLS instance. 
adding a new role is better, you can reuse the existing role and create a new one, how does it sound?

**Comment by dhayanands** [comment]
got it :) will go ahead and do the same :)

**Comment by dhayanands** [comment]
@zeusbaba tested the existing role with the slim installer and it works as expected. Think we dont need a new role just for the slim installer. 

Let me know if this issue can be closed.

**Comment by dhayanands** [comment]
created new role and got that merged to the develop branch.
